### ISSUE TITLE
SSH with putty only works sometimes

### ISSUE THREAD

**Issue by Soren90** [buptczq/WinCryptSSHAgent#1]
Hi

This may be caused by my impenitence when it comes to using smartcards in windows. But it the majority of times i use WinCryptSSHAgent with putty it doesnt work. I get this prompt:
![image](https://user-images.githubusercontent.com/36074299/61171756-54475700-a57c-11e9-91f8-b23e258f04b4.png)

The error message bellow shows up when i click ok. But when i click "Cancel" it works like 10% of the time. The other times i get the error "Pageant failed to provide a signature". Is my yubikey conflicting with some other device? I can't seem to figure it out. Any tips?

**Comment by buptczq** [comment]
Hello, it seems there is a software conflict. It turns out some software conflicts with WinCryptSSHAgent. For example: Pageant, OpenPGP, PuTTY-CAC's agent..... Do you have any other software using smartcards?

**Comment by Soren90** [comment]
This is what i can see in my device manager. I shouldn't have any other smartcard-devices or software. Not that im aware at least.

![image](https://user-images.githubusercontent.com/36074299/61173046-105d4d80-a58e-11e9-81c2-d6e28f27717c.png)

Is it supposed to be two devices?

**Comment by buptczq** [comment]
It's only one device. The smartcard reader is a virtual device associated with your smartcard.

**Comment by Soren90** [comment]
Could it be caused by that i've installed gnupg with putty support? I guess that should create a new smartcard, but could it conflict in some way?

**Comment by buptczq** [comment]
Bingo! Gnupg conflicts with windows smartcard driver, because it use a different smartcard protocol.

**Comment by Soren90** [comment]
I uninstalled gnupg and added that seems to have solved the issue. Thank you for the clarification!
