### ISSUE TITLE
32 bit build request

### ISSUE THREAD

**Issue by taxilian** [buptczq/WinCryptSSHAgent#11]
Hi,

I just got it to build with 32 bit go pretty easily and would like to ask if you'd consider putting out an installer for 32 bit =] I'm using a surface pro x, which is an arm64 processor but has 32 bit emulation support. Since golang isn't out for windows / arm64 having a build for 32 bit is the next best thing but at least lets us use the tool on this and other windows arm devices =]

Thanks for thinking about it!

**Comment by buptczq** [comment]
Hi, 32bit binary has been added in Pre-release v1.1.0
