### ISSUE TITLE
Possibility to implement GPG backend?

### ISSUE THREAD

**Issue by kaeltis** [buptczq/WinCryptSSHAgent#13]
Hi,

I just had a play around with WinCryptSSHAgent and I'm really liking it, however there seem to be some security issues with the current backend when using it with a Yubikey.
Compared to Gpg4win it uses the PIV functionality of a Yubikey instead of the GPG functionality. 

When using Gpg4win, the Yubikey always needs to be plugged in and the first access to the GPG key after restarting or plugging in the Yubikey needs to be validated by entering the GPG PIN. When pulling out the Yubikey no further key access is possible anymore, so no new SSH sessions can be created.

When using WinCryptSSHAgent, it seems the Yubikey only needs to be plugged in the very first time starting it. After that I can remove the Yubikey, close and restart WinCryptSSHAgent and I can still open new SSH sessions.

While this makes authentication a lot easier, it also seems to circumvents a lot of the added security a Yubikey offers. I'm no expert on this by any means, so maybe I just got something wrong.

Would it be possible to implement something that uses the GPG functionality of a Yubikey instead of PIV to have the added security of the PIN and allow no further access as soon as the key is removed?
All other existing solutions for WSL2 only hook into a running Gpg4win instance, but don't offer a true replacement, so this would really be awesome to have.

As a sidenote, using the GPG functionality of the Yubikey would also keep the same keys compared to Gpg4win, so no new keys would have to be placed on the servers when switching from Gpg4win to WinCryptSSHAgent.

**Comment by buptczq** [comment]
Hello,

It's weird, PIV mode requires PIN as well. After removing the Yubikey,  you will not be able to open a new SSH session. Are you sure you set the ssh agent and server correctly?

**Comment by kaeltis** [comment]
Oh wow, you are right, WinCryptSSHAgent seems to use a "MS-Organization-Access" certificate from my certificate store, but that's the only public key it shows, so it doesn't even detect the one on my yubikey.
