### ISSUE TITLE
Windows Defender报毒

### ISSUE THREAD

**Issue by dingwen07** [buptczq/WinCryptSSHAgent#14]
版本1.1.0.0 开启了Hyper-V agent
病毒类型: Trojan:Win32/Occamy.CAA
![image](https://user-images.githubusercontent.com/29778171/84996594-0d94b080-b180-11ea-8384-c08d189d830e.png)

**Comment by tmtron** [comment]
Also on my system Windows Defender reports that the [V1.1.0 WinCryptSSHAgent.exe
](https://github.com/buptczq/WinCryptSSHAgent/releases/download/v1.1.0/WinCryptSSHAgent.exe) contains a trojan
![image](https://user-images.githubusercontent.com/20422904/93705625-fa96d100-fb1e-11ea-98fd-7b8805cda9b0.png)

**Comment by michalsznajder** [comment]
I had the same. @buptczq are you sure you are malware free? A lot of people report problems with released binaries. I compiled from source just to be safe.

**Comment by buptczq** [comment]
> I had the same. @buptczq are you sure you are malware free? A lot of people report problems with released binaries. I compiled from source just to be safe.

I'm sure my computer is malware free. Nevertheless, I will create a clean environment to build released binaries.

**Comment by buptczq** [comment]
released binaries are built by github actions now
