### ISSUE TITLE
"Connection refused" to wincrypt-wsl.sock socket in WSL

### ISSUE THREAD

**Issue by Yggdrasil** [buptczq/WinCryptSSHAgent#17]
Hi, I'm having trouble getting WinCrypt SSH Agent to work. I'm trying to use it on Windows 10 2004 with WSL2 and Pageant. Pageant is set up to start and load my SSH key on login.

1. First I installed WinCrypt SSH Agent via chocolatey (as admin).
2. When starting the Agent I got an error that it couldn't create the .sock file in the `C:\ProgramData\chocolatey\lib\wincrypt-sshagent\tools\` directory. Makes sense, since that directory is only writeable by admins by default. So I granted `Users` write permission to that directory.
3. Starting the Agent then gave no more errors and I could see the .sock file was created.
4. When right-clicking the systray icon and showing public keys, I could see some key but not the key that was loaded into Pageant.
5. I added the SSH_AUTH_SOCK environment variable to my WSL2 shell (zsh on Ubuntu): `export SSH_AUTH_SOCK="/mnt/c/ProgramData/chocolatey/lib/wincrypt-sshagent/tools/wincrypt-wsl.sock"`

When testing via `ssh -Tv git@gitlab.com` I get a permission denied and the debug log shows `pubkey_prepare: ssh_get_authentication_socket: Connection refused`

The socket should be readable according to linux: `-rwxrwxrwx 1 martijn martijn 0 Jul 29 12:34 /mnt/c/ProgramData/chocolatey/lib/wincrypt-sshagent/tools/wincrypt-wsl.sock`

I'm not sure which part of the setup went wrong but it appears that my key from Pageant isn't visible to WinCrypt and that the socket is not responding to requests from apps in WSL.

I'd appreciate your help.

**Comment by MichaelHipp** [comment]
I'm having the same problem. Suggestions appreciated.

**Comment by cnf** [comment]
I have the same issue.

**Comment by michalsznajder** [comment]
What version are you using? 1.1.2 had broken WSL 1 support. Also I think Pagent is not required to run when Win Crypt SSH Agent is running.

**Comment by axxelG** [comment]
A bit late to the party, You described two different errors.

> I'm trying to use it on Windows 10 2004 with WSL2 and Pageant

WinCryptSSHAgent is designed to replace Pageant and use a key stored on a YubiKey. So WinCryptSSHAgent will not provide what you are looking for.

> I added the SSH_AUTH_SOCK environment variable to my WSL2 shell (zsh on Ubuntu): export SSH_AUTH_SOCK="/mnt/c/ProgramData/chocolatey/lib/wincrypt-sshagent/tools/wincrypt-wsl.sock"

To communicate with WSL2 you need to enable the "Hyper-V Agent" and use the  "WSL2 / Linux On Hyper-V Settings". The WSL(1) approach with the shared socket will not work with WSL2
