### ISSUE TITLE
Trojan:Win32/Ludicrouz.Z found in 1.0.2 release

### ISSUE THREAD

**Issue by mdekstrand** [buptczq/WinCryptSSHAgent#2]
Windows Defender blocks the 1.0.2 release binary, detecting [Trojan:Win32/Ludicrouz.Z] in it.

[Trojan:Win32/Ludicrouz.Z]: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fLudicrouz.Z&threatid=2147722906

**Comment by buptczq** [comment]
This seems a false positive, you can check out the scan results of virustotal:
https://www.virustotal.com/gui/file/a5d8706510b586ba05b2b7faa5b5aba6ee8e53717a17538fb0e90ef529467fdc/detection

Or you can review the code and complie it by your self.
