### ISSUE TITLE
Several virus checks flags for virus

### ISSUE THREAD

**Issue by jrylander** [buptczq/WinCryptSSHAgent#20]
See https://www.virustotal.com/gui/file/aaea99d492c7387ab0b0acc6ddcf54779197c4a0a04f1493927e494d042a932b/detection

Now, I don't think there is a virus but it is a nuissance. Tnx for the software! Very useful.

**Comment by axxelG** [comment]
I checke the current version on https://www.virustotal.com/
No errors were detected. I think this Issue can be closed.

**Comment by jrylander** [comment]
Ok to Close. Windows 10, v10.0.1.19042 does not complain either.
