### ISSUE TITLE
Limit SSHkey providers

### ISSUE THREAD

**Issue by flammehawk** [buptczq/WinCryptSSHAgent#22]
Hey, 
it would be great to Limit the source of the SSH keys  the agent provides.

Since Currently at my Work Pc it shows me a list of SSH keys that I have no glue about how they appeared their. 
And my Yubikey isn't even inserted. If I insert it I would think that it adds my Authkey to the list but it does not.

**Comment by flammehawk** [comment]
Okay, my mistake since it seems that I was using a Cert @home that I had no Clue about how it got their and thought it was my OpenPGP smartcard Auth key. 
It seems like this isn't the tool I want to use with a OpenPGP Smartcard. Maybe it could be clarified that you mean The PIV functionality of the yubikey and not the OpenPGP Smartcard functionality.

**Comment by nklamann** [comment]
This seems solved to me but I dont feel authorized to close it
