### ISSUE TITLE
Access denied for the pipe

### ISSUE THREAD

**Issue by Gaojianli** [buptczq/WinCryptSSHAgent#29]
While i try to launch, i see:
![image](https://user-images.githubusercontent.com/19235246/102323912-1134b300-3fbc-11eb-8d42-d934f8ae2849.png)
"Open as adminstrator" doesn't work.

Full control has been granted:
![image](https://user-images.githubusercontent.com/19235246/102324199-74264a00-3fbc-11eb-890d-249301ac51fe.png)

**Comment by sxul** [comment]
Check Task Manager, maybe the exe is already running

**Comment by Gaojianli** [comment]
> Check Task Manager, maybe the exe is already running

nope, I just rebooted, and this problem doesn't disappear.
![image](https://user-images.githubusercontent.com/19235246/102643135-c83a5580-4199-11eb-9de3-f180d121a55c.png)

**Comment by buptczq** [comment]
Check ```OpenSSH Authentication Agent``` service, it may use this pipe.

**Comment by Gaojianli** [comment]
> Check `OpenSSH Authentication Agent` service, it may use this pipe.

oh, yes, I enabled this service, after turned it off, this software works well. But what should I do if I want to run a OpenSSH server on this machine?

**Comment by buptczq** [comment]
> > Check `OpenSSH Authentication Agent` service, it may use this pipe.
> 
> oh, yes, I enabled this service, after turned it off, this software works well. But what should I do if I want to run a OpenSSH server on this machine?

```OpenSSH Authentication Agent``` service is useed to securely storing private keys, so it won't affect the OpenSSH server.

**Comment by Gaojianli** [comment]
I just followed this [guide](https://www.cnblogs.com/sparkdev/p/10166061.html)😒
Thanks for your help, I'll disable it.
