### ISSUE TITLE
support for mobaxterm

### ISSUE THREAD

**Issue by Gaojianli** [buptczq/WinCryptSSHAgent#3]
[MobaXterm](mobaxterm.mobatek.net/) is a very useful ssh client on Windows. It seems that its ssh module used putty(it uses putty ssh keys), however it doesn't work with WinCryptSSHAgent

**Comment by buptczq** [comment]
MobaXterm supports using Pageant as SSH agent according to `https://blog.mobatek.net/post/mobaxterm-new-release-8.2/`, which WinCryptSSHAgent also supports.
You can try to enable ` internal SSH agent ` option in MobaXterm. If it works, please tell me.

**Comment by Gaojianli** [comment]
It works, but I got an virus warning:
![image](https://user-images.githubusercontent.com/19235246/70123616-f859a800-16ad-11ea-84bc-9706a882eb6e.png)

**Comment by buptczq** [comment]
This seems a false positive because I don't have a valid digital certificate, you can check out the scan results of virustotal:
https://www.virustotal.com/gui/file/a5d8706510b586ba05b2b7faa5b5aba6ee8e53717a17538fb0e90ef529467fdc/detection
