### ISSUE TITLE
Show pulic keys 会把删除的key也展示出来

### ISSUE THREAD

**Issue by lostz** [buptczq/WinCryptSSHAgent#30]
请问这么删除,谢谢.

**Comment by buptczq** [comment]
WinCryptSSHAgent从windows的用户证书中读取证书列表，你可以Win+R运行```certmgr.msc```，在```个人```-```证书```中管理你的个人证书

-----------------------------------------

WinCryptSSHAgent loads the certificate list from windows certificate stores you can run ```certmgr.msc``` , and manage your personal certificate in ```Personal```-```Certificates```
