### ISSUE TITLE
Smart Card Service error

### ISSUE THREAD

**Issue by jozsefhabit** [buptczq/WinCryptSSHAgent#34]
Hello,

after the last 1.1.4 update on every authentication attempt a warning window appears saying "Smart Card Service is stopped! Do you want to restart it?" I have to 
The service itself is in Manual state by default, but it doesn't matter if I change it to Automatic or to any other startup type.

My OS version is: Windows 10 Home, Version 20H2, Build 19042.746

**Comment by buptczq** [comment]
If Smart Card Service is really stopped, WinCryptSSHAgent cannot work normally. Therefore, I added this feature.

There may still be bugs with this new feature. When the warning appears, is the Smart Card Service really stopped? Can you pass the authentication if you choose NO?

**Comment by jozsefhabit** [comment]
Thanks for your quick reply!

Yes, the service itself was stopped. Actually, I cannot start it permanently, it stops after several seconds. It means I have to click on the Ok or Cancel every time when I try to login to a server. Could not find any Smartcard related issues in the Event logs.

If I click on the Cancel, the authentication process continues.
If I click on the Ok, i'll have to go through an UAC warning that asks permission for the service restart, then it proceeds.

**Comment by buptczq** [comment]
It seems to be because of the Smart Card Service start and stop behavior:
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/hh849637(v%3Dws.11)#smart-card-service-start-and-stop-behavior

BTW, are you sure the authentication process can continue normally if you click on the Cancel? In my test,  the authentication failed when the Smart Card Service was stopped.

**Comment by jozsefhabit** [comment]
In my tests the authentication process continue normally, and I can log in successfully even if i click on the Cancel.

**Comment by jozsefhabit** [comment]
Just to clarify: I do not have any other fallback authentication mechanisms.
If I stop WinCryptSSHAgent I have to login with the password.
If WinCryptSSHAgent is running, then I can login to the servers even if I click on the Cancel button on the warning message.

**Comment by buptczq** [comment]
The feature is disabled in v1.1.5 release.

**Comment by jozsefhabit** [comment]
Thanks for your quick help, and for this great piece of software! :)
