### ISSUE TITLE
Exclude certificates with BitLocker/EFS EKU

### ISSUE THREAD

**Issue by vuori** [buptczq/WinCryptSSHAgent#4]
Certs used for disk encryption are usually not used for SSH, so I think filtering out ones that only have the BitLocker Drive Encryption (1.3.6.1.4.1.311.67.1.1) and/or Encrypting File System (1.3.6.1.4.1.311.10.3.4) EKU would make sense.

I can look into this if it sounds reasonable.

I guess the stricter alternative would be to accept only certs that have no EKU at all or include the Client Authentication (1.3.6.1.5.5.7.3.2) EKU.

**Comment by buptczq** [comment]
This feature has been added in v1.0.3.
