### ISSUE TITLE
Incompatible with SecureCRT 9.x

### ISSUE THREAD

**Issue by memchk** [buptczq/WinCryptSSHAgent#40]
It appears that SecureCRT integration does not work. The instructions in the program have you point to the WinSSH pipe, but according to this: https://forums.vandyke.com/showthread.php?p=54676, they use their own internal protocol.

I would suggest disabling the SecureCRT feature and removing it from the docs until proper support is implemented.

**Comment by buptczq** [comment]
What version of SecureCRT are you using? The version I use is Version 8.5.2 and it works fine.

**Comment by memchk** [comment]
Glad to hear it! I have version 9.0.0 build 2430, and it stalls on connect to a server. Maybe we need to update the documentation to advertise compatibility with 8.5.x specifically?

Btw, thank you for this utility, it has been very useful!

**Comment by buptczq** [comment]
I haven't updated to 9.0 yet. The protocol may have changed. I will try to be compatible with the new version in the future.

**Comment by memchk** [comment]
Understood. I will update the issue accordingly.

**Comment by buptczq** [comment]
Try v1.1.7 please.  If it works, please tell me.
[pre-released file](https://github.com/buptczq/WinCryptSSHAgent/releases/download/untagged-706e69051ac295a3a430/WinCryptSSHAgent.exe)

**Comment by memchk** [comment]
That works! Thanks for the help.
