### ISSUE TITLE
Getting "agent refused connection" error

### ISSUE THREAD

**Issue by omulmicsinegru** [buptczq/WinCryptSSHAgent#5]
Hello, 

OS: Windows 10
Build: 17134.1304

Thanks alot for writing this program. I stumbled upon it while trying to install pageant-weasel for my Yubikey. Sadly however i'm encountering a bit of a problem.  

I am trying to run the ssh-add command from Windows. 
When i do so ( having started WinCryptSSHAgent) i get the following error: 

![image](https://user-images.githubusercontent.com/10855580/75779398-d2e64400-5d59-11ea-8bc8-6e8e32121cf3.png)

I'm using the ssh-add that comes installed with Windows's implementation of OpenSSH. 

I am assuming that WinCryptSSHAgent is a drop-in replacement for the Windows10 ssh-agent.

**Comment by buptczq** [comment]
Hi,

WinCryptSSHAgent is a special ssh-agent and doesn't support ssh-add command, thus you see this error when using ssh-add. WinCryptSSHAgent is designed to use smartcard, i.e. Yubikey, to authenticate with SSH rather than using a local key file.

**Comment by buptczq** [comment]
Thanks for your feedback, the mechanism of UNIX socket may have changed in WSL 2. I will try to figure it out.

**Comment by dingwen07** [comment]
> Hello,
> 
> Thanks alot for the answer! .
> 
> I was trying to make this work on my WSL 2 setup and i found some weird behavior.
> 
> When i launch the ssh-add -l i get this message :
> ![image](https://user-images.githubusercontent.com/10855580/75912603-c513ea00-5e51-11ea-822f-4f2044b65b2d.png)
> 
> On the other hand , when i launch it from a WSL 1 instance, it works smoothly:
> ![image](https://user-images.githubusercontent.com/10855580/75912669-dd840480-5e51-11ea-91ed-9e6243c8503e.png)
> 
> I think i've identified a problem with WSL 2 , but i'm not knowledgeable enough to open a bug on their Repo.
> I'm posting it here maybe someone else will see it, or if you'd like to follow up on it :).
> 
> While this is magically fixed by people smarter than me i'll go back to using weasel-pagent so that i can stay on WSL 2.

Hi,
Although I have not used WSL2, according to the error message you provided, it seems that the problem you encountered in WSL2 may be that the local disk of Windows is not properly mounted in WSL, which is common for removable drives. Have you tried executing the program in a directory under C:?

**Comment by omulmicsinegru** [comment]
@dingwen07 i've tested on C: and sadly i get the same behavior :(

**Comment by vuori** [comment]
I don't use WSL2, but AFAIK it essentially runs in a cut-down Hyper-V VM. Unless MS has specifically implemented support, it seems unlikely that Unix domain sockets can reach from guest to host. Hyper-V sockets would probably work if supported by WSL2. They'd be useful reaching out to the agent from traditional VMs too, though a separate authentication step would be necessary.

**Comment by postwait** [comment]
Now that WSL2 is going to become the default -- this becomes much more important to solve.  I don't have any clue yet, but I thought I'd surface new context for concern.

**Comment by buptczq** [comment]
I'm working on solving the compatibility problem with WSL2 recently, WSL2 will be supported in the next version. It will even support sharing SSH keys with Hyper-V guest machines.

**Comment by buptczq** [comment]
Please try Pre-release v1.1.0

**Comment by omulmicsinegru** [comment]
Hello, 

I've tested with v1.1.0 and i do see some progress. 

However it doesn't seem to fully work. 
![image](https://user-images.githubusercontent.com/10855580/83964182-6aa08480-a8ab-11ea-8137-28bdcaee0d47.png)

As you can see i'm able to get the ssh-add command to run, and it does connect to the yubikey. 
Doing a git pull operation doesn't work though. 

Is there maybe an extra step that i missed?

**Comment by buptczq** [comment]
Have you added your public key to gitlab?

**Comment by omulmicsinegru** [comment]
yes, i have. This setup is working when i use weasel,

**Comment by buptczq** [comment]
could you run `ssh -vvv YOUR_GIT_SERVER` and provide the log to me?

**Comment by omulmicsinegru** [comment]
Sure, here it is.
[ssh-debug-output.txt](https://github.com/buptczq/WinCryptSSHAgent/files/4741647/ssh-debug-output.txt)

**Comment by buptczq** [comment]
It looks like the ssh client doesn't connect to the agent, please check your envs and settings.

**Comment by omulmicsinegru** [comment]
Can you please be a bit more specific on what settings i should look at ?

**Comment by buptczq** [comment]
The only thing I can know from the logs is that the ssh client is not connected to the agent. It's weird, but it doesn't look like a problem with this agent. You may check:

* if this agent is working properly on windows
* if there are other ssh agents running
* you should execute commands of `show WSL2 settings` every time you start a wsl2 session
* envs
* ~/.ssh/config
* ~/.bashrc
* .....

**Comment by sxul** [comment]
@omulmicsinegru Have you added some settings like `IdentitiesOnly=yes` in your `~/.ssh/config` file？

**Comment by omulmicsinegru** [comment]
@sxul no, i don't even have a ~/.ssh/config file...

@buptczq  thank you for your reply and sorry i couldn't get back to it sooner. 
Looking over the suggestion made me realize that it's probable that the GPG4WIN that i have installed and setup to use with Yubikey might mess us WinCrypt. 

I'll uninstall it and try again.
