### ISSUE TITLE
Exclude certificates without a private key

### ISSUE THREAD

**Issue by Gaojianli** [buptczq/WinCryptSSHAgent#9]
After an update of the windows, now this app will show all public key in the system, not only adobe but also microsoft,google,etc.
The issue #7 is also caused by this reason. I keep getting `Too many authentication failures` error during any login attempts.
![image](https://user-images.githubusercontent.com/19235246/82552736-451a3800-9b95-11ea-80ee-7afa29040596.png)

**Comment by buptczq** [comment]
What's the version of your Windows? I can't reproduce this problem in my computer.

**Comment by Gaojianli** [comment]
Version 10.0.19041.264

**Comment by buptczq** [comment]
This feature has been added in v1.0.4.

**Comment by Gaojianli** [comment]
Not work
